blank_issues_enabled: false
contact_links:
  - name: OpenWrt Forum thread (general questions / discussion)
    url: https://forum.openwrt.org/t/policy-based-routing-pbr-package-discussion/140639
    about: For usage questions and general discussion, please use the forum thread.
