#!/bin/sh /etc/rc.common
# Copyright 2017-2026 MOSSDeF, Stan Grishin (stangri@melmac.ca)
# shellcheck disable=SC2015,SC3043

# shellcheck disable=SC2034
START=20
# shellcheck disable=SC2034
USE_PROCD=1

if type extra_command 1>/dev/null 2>&1; then
	extra_command 'netifd' "Netifd extensions operations"
	extra_command 'on_interface_reload' "Run service on indicated interface reload"
	extra_command 'status' "Generates output required to troubleshoot routing issues
		Use '-d' option for more detailed output
		Use '-p' option to automatically upload data under PBR paste.ee account
			WARNING: while paste.ee uploads are unlisted, they are still publicly available
		List domain names after options to include their lookup in report"
	extra_command 'support' "Show diagnostic info and mask sensitive data"
	extra_command 'version' "Show version information"
else
# shellcheck disable=SC2034
	EXTRA_COMMANDS='help netifd on_interface_reload status version'
# shellcheck disable=SC2034
	EXTRA_HELP="
\tstatus\tGenerates output required to troubleshoot routing issues
\t\tUse '-d' option for more detailed output
\t\tUse '-p' option to automatically upload data under PBR paste.ee account
\t\t\tWARNING: while paste.ee uploads are unlisted, they are still publicly available
\t\tList domain names after options to include their lookup in report
\tsupport\tShow diagnostic info and mask sensitive data
"
fi

readonly packageName='pbr'
readonly _ucode="ucode -S -L /lib/${packageName} -L /lib/mwan4 /lib/${packageName}/cli.uc --"

# shellcheck disable=SC1091
. "${IPKG_INSTROOT}/lib/functions.sh"
# shellcheck disable=SC1091
. "${IPKG_INSTROOT}/lib/functions/network.sh"
# shellcheck disable=SC1091
. "${IPKG_INSTROOT}/usr/share/libubox/jshn.sh"

boot() { rc_procd start_service 'on_boot' && service_started 'on_boot'; }
# shellcheck disable=SC2120
start_service() {
	local param="${1:-on_start}"
	local result
	[ "$param" = 'on_boot' ] && return 0

	# Call ucode to do all work; it returns json_add_* shell commands
	result="$($_ucode start_service "$param" "$2")"
	# shellcheck disable=SC2181
	[ $? -eq 0 ] || return 1
	[ -n "$result" ] || return 0

	procd_open_instance 'main'
	procd_set_param command /bin/true
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_open_data
	eval "$result"
	procd_close_data
	procd_close_instance
	return 0
}
stop_service() { $_ucode stop_service; }
reload_service() { rc_procd start_service 'on_reload'; }
restart_service() { rc_procd start_service 'on_restart'; }
status_service() { $_ucode status_service "$@"; }
service_started() { [ "$1" = 'on_boot' ] && return 0; $_ucode service_started "$1"; }
service_triggers() {
	local procd_boot_trigger_delay procd_reload_delay n
	config_load "$packageName"
	config_get procd_boot_trigger_delay 'config' 'procd_boot_trigger_delay' '5000'
	config_get procd_reload_delay       'config' 'procd_reload_delay'       '0'

	if [ ! -s "/var/run/${packageName}.lock" ]; then
		printf 'Setting trigger (on_boot) '
		procd_add_raw_trigger "interface.*.up" "${procd_boot_trigger_delay}" "/etc/init.d/${packageName}" start && \
			printf '\033[0;32m\xe2\x9c\x93\033[0m\n' || printf '\033[0;31m\xe2\x9c\x97\033[0m\n'
	else
		PROCD_RELOAD_DELAY=$(( ${procd_reload_delay:-0} * 1000 ))
		procd_open_validate
			load_validate_config
			load_validate_policy
			load_validate_include
		procd_close_validate
		procd_open_trigger
			procd_add_config_trigger "config.change" 'openvpn' "/etc/init.d/${packageName}" reload 'on_openvpn_change'
			procd_add_config_trigger "config.change" "${packageName}" "/etc/init.d/${packageName}" reload
			if [ -n "$_pbr_ifaces_triggers" ]; then
				for n in $_pbr_ifaces_triggers; do
					procd_add_interface_trigger "interface.*" "$n" "/etc/init.d/${packageName}" on_interface_reload "$n"
				done
			fi
		procd_close_trigger
	fi
}
netifd()  { $_ucode netifd "$@"; }
on_interface_reload() {
	if [ ! -e "/var/run/${packageName}.lock" ]; then
		logger -t "$packageName" "Reload on interface change aborted: service is stopped."
		return 0
	else
		rc_procd start_service 'on_interface_reload' "$1"
	fi
}
support() { $_ucode support "$@"; }
version() { $_ucode version "$@"; }

# shellcheck disable=SC2120
load_validate_config() {
	uci_load_validate "$packageName" "$packageName" "$1" "${2}${3:+ ${3}}" \
		'enabled:bool:0' \
		'strict_enforcement:bool:1' \
		'ipv6_enabled:bool:0' \
		'resolver_set:or("", "none", "dnsmasq.nftset")' \
		'resolver_instance:list(or(integer, string)):*' \
		'verbosity:range(0,2):2' \
		'uplink_mark:regex("[A-Fa-f0-9]{8}"):00010000' \
		'uplink_ip_rules_priority:range(1001,32765):30000' \
		'fw_mask:regex("[A-Fa-f0-9]{8}"):00ff0000' \
		'icmp_interface:or("", tor, uci("network", "@interface"))' \
		'ignored_interface:list(or(tor, uci("network", "@interface")))' \
		'supported_interface:list(or(ignore, tor, regex("xray_.*"), uci("network", "@interface")))' \
		'procd_boot_trigger_delay:range(1000,10000):5000' \
		'prefixlength:uinteger:1' \
		'lan_device:list(or(network)):br-lan' \
		'procd_reload_delay:uinteger:0' \
		'uplink_interface:network:wan' \
		'uplink_interface6:network:wan6' \
		'webui_supported_protocol:list(string)' \
		'debug_performance:bool:0'\
		'nft_rule_counter:bool:0'\
		'nft_set_auto_merge:bool:1'\
		'nft_set_counter:bool:0'\
		'nft_set_flags_interval:bool:1'\
		'nft_set_flags_timeout:bool:0'\
		'nft_set_gc_interval:or("", string)'\
		'nft_set_policy:or("", memory, performance):performance'\
		'nft_set_timeout:or("", string)' \
	;
}

# shellcheck disable=SC2120
load_validate_dns_policy() {
	local name
	local enabled
	local src_addr
	local dest_dns
	local dest_dns_port
	uci_load_validate "$packageName" 'dns_policy' "$1" "${2}${3:+ ${3}}" \
		'name:string:Untitled' \
		'enabled:bool:1' \
		'src_addr:list(neg(or(host,network,macaddr,string)))' \
		'dest_dns:list(or(host,network,string))' \
		'dest_dns_port:port:53' \
	;
}

# shellcheck disable=SC2120
load_validate_policy() {
	local name
	local enabled
	local interface
	local proto
	local chain
	local src_addr
	local src_port
	local dest_addr
	local dest_port
	uci_load_validate "$packageName" 'policy' "$1" "${2}${3:+ ${3}}" \
		'name:string:Untitled' \
		'enabled:bool:1' \
		'interface:or("ignore", "tor", regex("xray_.*"), uci("network", "@interface")):wan' \
		'proto:or(string)' \
		'chain:or("", "forward", "output", "prerouting"):prerouting' \
		'src_addr:list(neg(or(host,network,macaddr,string)))' \
		'src_port:list(neg(or(portrange,string)))' \
		'dest_addr:list(neg(or(host,network,string)))' \
		'dest_port:list(neg(or(portrange,string)))' \
	;
}

# shellcheck disable=SC2120
load_validate_include() {
	local path=
	local enabled=
	uci_load_validate "$packageName" 'include' "$1" "${2}${3:+ ${3}}" \
		'path:file' \
		'enabled:bool:0' \
	;
}
